# Generated by Django 4.1.3 on 2022-12-04 15:28

from django.db import migrations, models
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('domain', models.CharField(max_length=60)),
                ('country', django_countries.fields.CountryField(blank=True, db_index=True, max_length=2, null=True)),
            ],
        ),
    ]
